"""Add CourseAnnouncement model

Revision ID: 3efa224581f4
Revises: 88284d4b0929
Create Date: 2026-04-28 01:05:53.729127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3efa224581f4'
down_revision: Union[str, None] = '88284d4b0929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('lecturer_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('announcement_type', sa.String(), nullable=True),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_announcements_course_id'), 'course_announcements', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_announcements_lecturer_id'), 'course_announcements', ['lecturer_id'], unique=False)
    op.drop_index('ix_template_profiles_id', table_name='template_profiles')
    op.drop_index('ix_template_profiles_school', table_name='template_profiles')
    op.drop_index('ix_template_profiles_university_id', table_name='template_profiles')
    op.drop_table('template_profiles')
    op.drop_index('ix_sis_api_keys_hash', table_name='sis_api_keys')
    op.drop_index('ix_sis_api_keys_id', table_name='sis_api_keys')
    op.drop_index('ix_sis_api_keys_university', table_name='sis_api_keys')
    op.drop_index('ix_sis_api_keys_university_id', table_name='sis_api_keys')
    op.drop_table('sis_api_keys')
    op.alter_column('courses', 'shared_with_department_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('timetable_slots', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timetable_slots', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('courses', 'shared_with_department_ids',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_table('sis_api_keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('university_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('key_prefix', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('key_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='sis_api_keys_created_by_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], name='sis_api_keys_university_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sis_api_keys_pkey'),
    sa.UniqueConstraint('key_hash', name='sis_api_keys_key_hash_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_sis_api_keys_university_id', 'sis_api_keys', ['university_id'], unique=False)
    op.create_index('ix_sis_api_keys_university', 'sis_api_keys', ['university_id'], unique=False)
    op.create_index('ix_sis_api_keys_id', 'sis_api_keys', ['id'], unique=False)
    op.create_index('ix_sis_api_keys_hash', 'sis_api_keys', ['key_hash'], unique=False)
    op.create_table('template_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('university_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('school_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('original_filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('shape', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('containers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='template_profiles_created_by_id_fkey'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], name='template_profiles_university_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='template_profiles_pkey')
    )
    op.create_index('ix_template_profiles_university_id', 'template_profiles', ['university_id'], unique=False)
    op.create_index('ix_template_profiles_school', 'template_profiles', ['school_name'], unique=False)
    op.create_index('ix_template_profiles_id', 'template_profiles', ['id'], unique=False)
    op.drop_index(op.f('ix_course_announcements_lecturer_id'), table_name='course_announcements')
    op.drop_index(op.f('ix_course_announcements_course_id'), table_name='course_announcements')
    op.drop_table('course_announcements')
    # ### end Alembic commands ###
