"""add_user_audit_timestamps

Revision ID: 62bec6a9d2c1
Revises: b679af0f9f03
Create Date: 2026-05-13 21:13:24.263967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62bec6a9d2c1'
down_revision: Union[str, None] = 'b679af0f9f03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sis_api_keys_hash', table_name='sis_api_keys')
    op.drop_index('ix_sis_api_keys_id', table_name='sis_api_keys')
    op.drop_index('ix_sis_api_keys_university', table_name='sis_api_keys')
    op.drop_index('ix_sis_api_keys_university_id', table_name='sis_api_keys')
    op.drop_table('sis_api_keys')
    op.drop_index('ix_courses_code', table_name='courses')
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=False)
    op.create_unique_constraint('uq_course_dept_code', 'courses', ['department_id', 'code'])
    op.drop_constraint('departments_code_key', 'departments', type_='unique')
    op.drop_constraint('departments_name_key', 'departments', type_='unique')
    op.create_unique_constraint('uq_dept_univ_code', 'departments', ['university_id', 'code'])
    op.create_unique_constraint('uq_dept_univ_name', 'departments', ['university_id', 'name'])
    op.drop_constraint('exam_periods_created_by_id_fkey', 'exam_periods', type_='foreignkey')
    op.drop_column('exam_periods', 'created_by_id')
    op.drop_column('exam_periods', 'published_at')
    op.drop_index('ix_rooms_name', table_name='rooms')
    op.create_index(op.f('ix_rooms_name'), 'rooms', ['name'], unique=False)
    op.create_unique_constraint('uq_room_univ_name', 'rooms', ['university_id', 'name'])
    op.drop_constraint('student_groups_name_key', 'student_groups', type_='unique')
    op.create_unique_constraint('uq_student_group_univ_name', 'student_groups', ['university_id', 'name'])
    op.drop_constraint('fk_students_university_id', 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'universities', ['university_id'], ['id'])
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key('fk_students_university_id', 'students', 'universities', ['university_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uq_student_group_univ_name', 'student_groups', type_='unique')
    op.create_unique_constraint('student_groups_name_key', 'student_groups', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_room_univ_name', 'rooms', type_='unique')
    op.drop_index(op.f('ix_rooms_name'), table_name='rooms')
    op.create_index('ix_rooms_name', 'rooms', ['name'], unique=True)
    op.add_column('exam_periods', sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('exam_periods', sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('exam_periods_created_by_id_fkey', 'exam_periods', 'users', ['created_by_id'], ['id'])
    op.drop_constraint('uq_dept_univ_name', 'departments', type_='unique')
    op.drop_constraint('uq_dept_univ_code', 'departments', type_='unique')
    op.create_unique_constraint('departments_name_key', 'departments', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('departments_code_key', 'departments', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_course_dept_code', 'courses', type_='unique')
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.create_index('ix_courses_code', 'courses', ['code'], unique=True)
    op.create_table('sis_api_keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('university_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('key_prefix', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('key_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='sis_api_keys_created_by_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], name='sis_api_keys_university_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sis_api_keys_pkey'),
    sa.UniqueConstraint('key_hash', name='sis_api_keys_key_hash_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_sis_api_keys_university_id', 'sis_api_keys', ['university_id'], unique=False)
    op.create_index('ix_sis_api_keys_university', 'sis_api_keys', ['university_id'], unique=False)
    op.create_index('ix_sis_api_keys_id', 'sis_api_keys', ['id'], unique=False)
    op.create_index('ix_sis_api_keys_hash', 'sis_api_keys', ['key_hash'], unique=False)
    # ### end Alembic commands ###
