"""Add University tenant model and foreign keys

Revision ID: 8e6e4dd249bd
Revises: af108f22f33c
Create Date: 2026-03-15 13:19:18.538161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e6e4dd249bd'
down_revision: Union[str, None] = 'af108f22f33c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_universities_id'), 'universities', ['id'], unique=False)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="timestamp::timestamp with time zone")
    op.add_column('departments', sa.Column('university_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_departments_university_id'), 'departments', ['university_id'], unique=False)
    op.create_foreign_key(None, 'departments', 'universities', ['university_id'], ['id'])
    op.alter_column('lecturers', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at::timestamp with time zone")
    op.alter_column('notifications', 'read_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="read_at::timestamp with time zone")
    op.add_column('rooms', sa.Column('university_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_rooms_university_id'), 'rooms', ['university_id'], unique=False)
    op.create_foreign_key(None, 'rooms', 'universities', ['university_id'], ['id'])
    op.alter_column('students', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="created_at::timestamp with time zone")
    op.add_column('template_profiles', sa.Column('university_id', sa.Integer(), nullable=True))
    op.alter_column('template_profiles', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at::timestamp with time zone")
    op.create_index(op.f('ix_template_profiles_university_id'), 'template_profiles', ['university_id'], unique=False)
    op.create_foreign_key(None, 'template_profiles', 'universities', ['university_id'], ['id'])
    op.add_column('timetable_slots', sa.Column('shared_group_ids', sa.JSON(), nullable=True))
    op.add_column('timetable_slots', sa.Column('combined_size', sa.Integer(), nullable=True))
    op.add_column('timetable_slots', sa.Column('shared_batch_id', sa.Integer(), nullable=True))
    op.create_index('ix_slot_batch', 'timetable_slots', ['timetable_id', 'shared_batch_id'], unique=False)
    op.create_index(op.f('ix_timetable_slots_shared_batch_id'), 'timetable_slots', ['shared_batch_id'], unique=False)
    op.alter_column('timetable_versions', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at::timestamp with time zone")
    op.add_column('timetables', sa.Column('university_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_timetables_university_id'), 'timetables', ['university_id'], unique=False)
    op.create_foreign_key(None, 'timetables', 'universities', ['university_id'], ['id'])
    op.add_column('users', sa.Column('university_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_university_id'), 'users', ['university_id'], unique=False)
    op.create_foreign_key(None, 'users', 'universities', ['university_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_university_id'), table_name='users')
    op.drop_column('users', 'university_id')
    op.drop_constraint(None, 'timetables', type_='foreignkey')
    op.drop_index(op.f('ix_timetables_university_id'), table_name='timetables')
    op.drop_column('timetables', 'university_id')
    op.alter_column('timetable_versions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index(op.f('ix_timetable_slots_shared_batch_id'), table_name='timetable_slots')
    op.drop_index('ix_slot_batch', table_name='timetable_slots')
    op.drop_column('timetable_slots', 'shared_batch_id')
    op.drop_column('timetable_slots', 'combined_size')
    op.drop_column('timetable_slots', 'shared_group_ids')
    op.drop_constraint(None, 'template_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_template_profiles_university_id'), table_name='template_profiles')
    op.alter_column('template_profiles', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('template_profiles', 'university_id')
    op.alter_column('students', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_index(op.f('ix_rooms_university_id'), table_name='rooms')
    op.drop_column('rooms', 'university_id')
    op.alter_column('notifications', 'read_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('lecturers', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_index(op.f('ix_departments_university_id'), table_name='departments')
    op.drop_column('departments', 'university_id')
    op.alter_column('audit_logs', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index(op.f('ix_universities_id'), table_name='universities')
    op.drop_table('universities')
    # ### end Alembic commands ###
