"""Add rotation_cycle_length and rotation_configuration to LabSession

Revision ID: a99ccfc24cc7
Revises: dea511713a22
Create Date: 2026-06-21 17:02:17.992499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a99ccfc24cc7'
down_revision: Union[str, None] = 'dea511713a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sis_api_keys_hash', table_name='sis_api_keys')
    op.drop_index('ix_sis_api_keys_id', table_name='sis_api_keys')
    op.drop_index('ix_sis_api_keys_university', table_name='sis_api_keys')
    op.drop_index('ix_sis_api_keys_university_id', table_name='sis_api_keys')
    op.drop_table('sis_api_keys')
    op.add_column('lab_sessions', sa.Column('rotation_cycle_length', sa.Integer(), server_default='1', nullable=False))
    op.add_column('lab_sessions', sa.Column('rotation_configuration', sa.JSON(), nullable=True))
    op.drop_column('lab_sessions', 'rotation_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_sessions', sa.Column('rotation_order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('lab_sessions', 'rotation_configuration')
    op.drop_column('lab_sessions', 'rotation_cycle_length')
    op.create_table('sis_api_keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('university_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('key_prefix', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('key_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='sis_api_keys_created_by_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], name='sis_api_keys_university_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sis_api_keys_pkey'),
    sa.UniqueConstraint('key_hash', name='sis_api_keys_key_hash_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_sis_api_keys_university_id', 'sis_api_keys', ['university_id'], unique=False)
    op.create_index('ix_sis_api_keys_university', 'sis_api_keys', ['university_id'], unique=False)
    op.create_index('ix_sis_api_keys_id', 'sis_api_keys', ['id'], unique=False)
    op.create_index('ix_sis_api_keys_hash', 'sis_api_keys', ['key_hash'], unique=False)
    # ### end Alembic commands ###
