"""add chief_invigilator_id to exam_slots

Revision ID: a9ee854b9a69
Revises: 023bbafa2c3e
Create Date: 2026-05-25 01:24:50.377818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9ee854b9a69'
down_revision: Union[str, None] = '023bbafa2c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_slots', sa.Column('chief_invigilator_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_exam_slots_chief_invigilator_id'), 'exam_slots', ['chief_invigilator_id'], unique=False)
    op.create_foreign_key(None, 'exam_slots', 'lecturers', ['chief_invigilator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exam_slots', type_='foreignkey')
    op.drop_index(op.f('ix_exam_slots_chief_invigilator_id'), table_name='exam_slots')
    op.drop_column('exam_slots', 'chief_invigilator_id')
    # ### end Alembic commands ###
