"""Add LabSession model for smart lab scheduling

Revision ID: dea511713a22
Revises: c4f5d6e7a8b9
Create Date: 2026-06-20 22:40:52.165089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dea511713a22'
down_revision: Union[str, None] = 'c4f5d6e7a8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('session_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('frequency_weeks', sa.Integer(), nullable=False),
    sa.Column('rotation_order', sa.Integer(), nullable=True),
    sa.Column('has_conflict', sa.Boolean(), nullable=False),
    sa.Column('conflict_detail', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['student_groups.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lab_session_group_course', 'lab_sessions', ['group_id', 'course_id'], unique=False)
    op.create_index('ix_lab_session_room_day', 'lab_sessions', ['room_id', 'day_of_week'], unique=False)
    op.create_index('ix_lab_session_timetable', 'lab_sessions', ['timetable_id'], unique=False)
    op.create_index('ix_lab_session_university_day', 'lab_sessions', ['university_id', 'day_of_week'], unique=False)
    op.create_index(op.f('ix_lab_sessions_course_id'), 'lab_sessions', ['course_id'], unique=False)
    op.create_index(op.f('ix_lab_sessions_group_id'), 'lab_sessions', ['group_id'], unique=False)
    op.create_index(op.f('ix_lab_sessions_id'), 'lab_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_lab_sessions_room_id'), 'lab_sessions', ['room_id'], unique=False)
    op.create_index(op.f('ix_lab_sessions_timetable_id'), 'lab_sessions', ['timetable_id'], unique=False)
    op.create_index(op.f('ix_lab_sessions_university_id'), 'lab_sessions', ['university_id'], unique=False)
    op.drop_table('tenant_access_links')
    op.drop_index('ix_sis_api_keys_hash', table_name='sis_api_keys')
    op.drop_index('ix_sis_api_keys_id', table_name='sis_api_keys')
    op.drop_index('ix_sis_api_keys_university', table_name='sis_api_keys')
    op.drop_index('ix_sis_api_keys_university_id', table_name='sis_api_keys')
    op.drop_table('sis_api_keys')
    op.drop_constraint('uq_course_dept_code', 'courses', type_='unique')
    op.drop_index('ix_courses_code', table_name='courses')
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=True)
    op.drop_constraint('uq_dept_univ_code', 'departments', type_='unique')
    op.drop_constraint('uq_dept_univ_name', 'departments', type_='unique')
    op.create_unique_constraint(None, 'departments', ['name'])
    op.create_unique_constraint(None, 'departments', ['code'])
    op.drop_constraint('plan_quotas_created_by_id_fkey', 'plan_quotas', type_='foreignkey')
    op.drop_column('plan_quotas', 'published_at')
    op.drop_column('plan_quotas', 'created_by_id')
    op.alter_column('platform_alerts', 'auto_resolve',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index('ix_platform_alerts_key', table_name='platform_alerts')
    op.drop_index('ix_platform_alerts_resolved', table_name='platform_alerts')
    op.drop_index('ix_platform_alerts_alert_key', table_name='platform_alerts')
    op.create_index(op.f('ix_platform_alerts_alert_key'), 'platform_alerts', ['alert_key'], unique=True)
    op.drop_constraint('uq_room_univ_name', 'rooms', type_='unique')
    op.drop_index('ix_rooms_name', table_name='rooms')
    op.create_index(op.f('ix_rooms_name'), 'rooms', ['name'], unique=True)
    op.drop_constraint('uq_student_group_univ_name', 'student_groups', type_='unique')
    op.create_unique_constraint(None, 'student_groups', ['name'])
    op.drop_column('student_groups', 'custom_subtype')
    op.drop_index('ix_students_university_id', table_name='students')
    op.drop_constraint('students_university_id_fkey', 'students', type_='foreignkey')
    op.drop_column('students', 'university_id')
    op.drop_column('universities', 'onboarding_completed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('universities', sa.Column('onboarding_completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('university_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('students_university_id_fkey', 'students', 'universities', ['university_id'], ['id'])
    op.create_index('ix_students_university_id', 'students', ['university_id'], unique=False)
    op.add_column('student_groups', sa.Column('custom_subtype', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'student_groups', type_='unique')
    op.create_unique_constraint('uq_student_group_univ_name', 'student_groups', ['university_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_rooms_name'), table_name='rooms')
    op.create_index('ix_rooms_name', 'rooms', ['name'], unique=False)
    op.create_unique_constraint('uq_room_univ_name', 'rooms', ['university_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_platform_alerts_alert_key'), table_name='platform_alerts')
    op.create_index('ix_platform_alerts_alert_key', 'platform_alerts', ['alert_key'], unique=False)
    op.create_index('ix_platform_alerts_resolved', 'platform_alerts', ['resolved_at'], unique=False)
    op.create_index('ix_platform_alerts_key', 'platform_alerts', ['alert_key'], unique=False)
    op.alter_column('platform_alerts', 'auto_resolve',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('plan_quotas', sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('plan_quotas', sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_foreign_key('plan_quotas_created_by_id_fkey', 'plan_quotas', 'users', ['created_by_id'], ['id'])
    op.drop_constraint(None, 'departments', type_='unique')
    op.drop_constraint(None, 'departments', type_='unique')
    op.create_unique_constraint('uq_dept_univ_name', 'departments', ['university_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('uq_dept_univ_code', 'departments', ['university_id', 'code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.create_index('ix_courses_code', 'courses', ['code'], unique=False)
    op.create_unique_constraint('uq_course_dept_code', 'courses', ['department_id', 'code'], postgresql_nulls_not_distinct=False)
    op.create_table('sis_api_keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('university_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('key_prefix', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('key_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='sis_api_keys_created_by_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], name='sis_api_keys_university_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sis_api_keys_pkey'),
    sa.UniqueConstraint('key_hash', name='sis_api_keys_key_hash_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_sis_api_keys_university_id', 'sis_api_keys', ['university_id'], unique=False)
    op.create_index('ix_sis_api_keys_university', 'sis_api_keys', ['university_id'], unique=False)
    op.create_index('ix_sis_api_keys_id', 'sis_api_keys', ['id'], unique=False)
    op.create_index('ix_sis_api_keys_hash', 'sis_api_keys', ['key_hash'], unique=False)
    op.create_table('tenant_access_links',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('university_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], name='tenant_access_links_university_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tenant_access_links_pkey'),
    sa.UniqueConstraint('token', name='tenant_access_links_token_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_lab_sessions_university_id'), table_name='lab_sessions')
    op.drop_index(op.f('ix_lab_sessions_timetable_id'), table_name='lab_sessions')
    op.drop_index(op.f('ix_lab_sessions_room_id'), table_name='lab_sessions')
    op.drop_index(op.f('ix_lab_sessions_id'), table_name='lab_sessions')
    op.drop_index(op.f('ix_lab_sessions_group_id'), table_name='lab_sessions')
    op.drop_index(op.f('ix_lab_sessions_course_id'), table_name='lab_sessions')
    op.drop_index('ix_lab_session_university_day', table_name='lab_sessions')
    op.drop_index('ix_lab_session_timetable', table_name='lab_sessions')
    op.drop_index('ix_lab_session_room_day', table_name='lab_sessions')
    op.drop_index('ix_lab_session_group_course', table_name='lab_sessions')
    op.drop_table('lab_sessions')
    # ### end Alembic commands ###
